version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gospelmus_app
    volumes:
      - .:/var/www/html
    ports:
      - "9010:9000"
    environment:
      - PHP_EXTENSION_DIR=/usr/local/lib/php/extensions/no-debug-non-zts-20200930
    depends_on:
      - mysql
      - redis
    networks:
      - gospelmus_net

  webserver:
    image: nginx:alpine
    container_name: gospelmus_webserver
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7777:80"
    depends_on:
      - app
    networks:
      - gospelmus_net

  mysql:
    image: mysql:5.7
    container_name: gospelmus_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gospelmus
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3352:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gospelmus_net

  redis:
    image: redis:alpine
    container_name: gospelmus_redis
    ports:
      - "6381:6379" # Porta ajustada
    networks:
      - gospelmus_net

volumes:
  mysql_data:

networks:
  gospelmus_net:
